### ISSUE TITLE
Add license? (Might want to "vendor" i.e. copy into Racket Mode)

### ISSUE THREAD

**Issue by greghendershott** [rmculpepper/custom-load#4]
Hello and sorry to bother you.

For https://github.com/greghendershott/racket-mode/issues/730 and more specifically https://github.com/greghendershott/racket-mode/issues/41, I'm considering doing something like your compiled load handler.

For various reasons[^1][^2] it's impractical for Racket Mode to depend on Racket packages via `raco pkg`. As a result, I would need to "vendor" the code, i.e. copy it. I might go on to modify it somewhat, but the original copying would need to be kosher wrt to license. Since Racket Mode for Emacs is GPL, I'd need your code to be GPL or MIT, for example. Unfortunately I don't see an explicit license for your code.

Would you be OK with adding such a license?

(To be clear I'm not yet 100% sure I'd go on to use this. But even the decision process would involve copying, committing to a topic branch, and testing; I'd feel uncomfortable doing even that w/o a license.  Anyway a clear license might help someone else someday.)

Thank you for considering my request.

[^1]: Racket Mode's combination of Emacs Lisp and Racket code is delivered as an Emacs package -- not installed via `raco pkg`. 

[^2]: Racket Mode endeavors to support fairly old versions of Racket, and it has been simpler to avoid also dealing with various versions of packages.

**Comment by rmculpepper** [comment]
No problem. I've added a license declaration to info.rkt and as comment headers to the *.rkt files.

**Comment by greghendershott** [comment]
Thank you!
